### ISSUE TITLE
Make the Client/Websocket more resilient to connection Issues.

### ISSUE THREAD

**Issue by KeyboardInterrupt** [AlbianWarp/AlbianWarpClient#23]
~~**Websocket sometimes dies with  'invalid closing frame code'**~~
~~We should investigate why that happens, and also we should try to open up a new socket when it happens!~~
I suppose this was related to the Bonkers Server.
The Websocket should be able to recover from a connection loss non the less, This Issue will be made into a feature request. to make the Websocket more resilient.

**Comment by KeyboardInterrupt** [comment]
I suppose this was related to the Bonkers Server.
The Websocket should be able to recover from a connection loss non the less, This Issue will be made into a feature request. to make the Websocket more resilient.

**Comment by Amaikokonut** [comment]
Yeah I haven't noticed this at all since the new server either! But the more resilience the better :D

**Comment by KeyboardInterrupt** [comment]
resolved by #34
