### ISSUE TITLE
Let the client only update the ingame Contacts on Changes

### ISSUE THREAD

**Issue by KeyboardInterrupt** [AlbianWarp/AlbianWarpClient#26]
Currently the Client is Hammering the Contact update script like crazy!
To not slow down the game unnecessarily, we should only trigger this upon a change, i.e. every time a players online status changed, or a new player is added to the List.

**Comment by Amaikokonut** [comment]
To help with this, in the latest working CAOS branch there is a script in the new WWR agent, 1008, that the client could trigger when a person's online status changes.
Example: `mesg wrt+ game "aw_wwr_agent" 1008 "Aiko" "online" 0`
p1 is the username, p2 is either "online" or "offline"
If this line is used to only update on status changes, it will greatly reduce the load on the engine.

**Comment by Amaikokonut** [comment]
To be more specific, this is how I imagine this working: 

- Whenever the user goes online, that is when they will be pushed the contacts list and the _status variables will be updated-- just like they are now, not using the 1008 script.
- If a new user is registered while the client is connected, the client will mesg writ the new contact.
- If a contact changes status while the client is still connected, (IE goes online when they were previously offline or vice versa), the client will mesg writ the 1008 script mentioned above. This will also trigger all WWR agents connected to that user.

**Comment by KeyboardInterrupt** [comment]
This is made obsolete by the Switch to ReBabel
