### ISSUE TITLE
Add a GUI to the AlbianWarp Client

### ISSUE THREAD

**Issue by KeyboardInterrupt** [AlbianWarp/AlbianWarpClient#33]
While functioning fine as a console application, the client should non the less provide a GUI.

Having a GUI would allow for easy access to i.E. the Configuration.
Also the usability and presentation could be greatly enhanced.

**Comment by Amaikokonut** [comment]
If I run out of things to do before you do, I might like to experiment with this too.

**Comment by KeyboardInterrupt** [comment]
This is made obsolete by the Switch to ReBabel
