### ISSUE TITLE
Trying to warp a creature with a strange character in the name crashes the client

### ISSUE THREAD

**Issue by Amaikokonut** [AlbianWarp/AlbianWarpClient#35]
![image](https://user-images.githubusercontent.com/34694450/39966838-49ed2d58-5680-11e8-861f-b03a1a2ceaa6.png)
![image](https://user-images.githubusercontent.com/34694450/39966833-3d985604-5680-11e8-951c-c33ee8cbb4d5.png)

**Comment by KeyboardInterrupt** [comment]
This is made obsolete by the Switch to ReBabel
