### ISSUE TITLE
Client notifying the engine of incoming events (and generally communicating better)

### ISSUE THREAD

**Issue by Amaikokonut** [AlbianWarp/AlbianWarpClient#36]
If the client could notify the engine of incoming creatures, DMAs, RTDMAs, and other stuff via a MESG WRIT/WRT+, it would make receiving/interpreting messages a lot faster and save the engine a lot of resources ticking through a long timer script.

Paired with SMAs (#32), this could establish a closer relationship between the client and engine and be used to handle problems such as creatures that don't warp in/out properly.

**Comment by Amaikokonut** [comment]
An example of how mesg/SMA communication could maybe work?:

- Client mesg writs the immigrant-checker with a incoming creature to import and adds that creature to an "awaiting confirmation" list.
- The immigrant checker successfully warps in the creature and creates an SMA with the creature's moniker/filename
- The client finds the SMA, kills it, and removes the creature from the "awaiting confirmation" list

or:
- Client mesg writs the immigrant-checker with a incoming creature to import and adds that creature to an "awaiting confirmation" list.
- The immigrant checker tries to warp in the creature, but a copy of that creature already exists in their world and it cannot be warped in. It creates an SMA to tell the client that. 
- The client finds the SMA, kills it, removes the creature from the "awaiting confirmation" list and puts it on a "waiting to move" list.
- The client checks the "waiting to move" list and attempts to move that creature file from the "My Creatures" folder to a subfolder (titled "Duplicate Warp Creatures" or something). When it succeeds, the creature is removed from the "waiting to move" list. This might take a few tries and might not actually happen until the next engine restart if the engine currently has a lock on that file.

or:
- Client mesg writs the immigrant-checker with a incoming creature to import and adds that creature to an "awaiting confirmation" list.
- The engine does nothing, for some reason.
- Several seconds later, during its routines, the client checks the "awaiting confirmation" list and notices the creature is still on the list. It checks to see if the creature file still exists in the My Creatures folder and if not, assumes the user removed or deleted it and removes the entry from the "awaiting confirmation" list.
- If the creature file is still there, the client attempts to mesg writ the immigrant-checker with the incoming creature again.
- The engine still does nothing for some reason.
- After three or so attempts at this, the client assumes there is something wrong with the game, either the immigrant checker autokilled and isn't recovering, or something went wrong in the script. It throws an error.

**Comment by KeyboardInterrupt** [comment]
I like this Idea, The whole `MESG WRT+` Thing is something we should use more, it would reduce the constant hammering on the Engine by the Tick timers and constantly checking threads inside the client.

This will allow us to make the client a lot more elegant.
Also Having a state representation for creatures makes the whole construct more robust, we should do more stuff like this XD.

:+1:

**Comment by KeyboardInterrupt** [comment]
This is made obsolete by the Switch to ReBabel
