### ISSUE TITLE
Add a README.md and LICENSE.md 

### ISSUE THREAD

**Issue by KeyboardInterrupt** [AlbianWarp/AlbianWarpClient#4]
This project needs a README.md
also a LICENSE.md is needed showing that this Project is licensed under __GPL3__

**Comment by JennaMalkin** [comment]
NB: Make sure your Anti-Virus Software (looking at you AVAST) is not set to aggressively auto-quarantine every slightly non-professional .exe it comes across.  Also if on Windows 10, running the Albian Warp Client as an administrator may help.

**Comment by KeyboardInterrupt** [comment]
#19 awaiting review

**Comment by KeyboardInterrupt** [comment]
done
