### ISSUE TITLE
Dectect the switch of Worlds, and if the Player is on the Menu Screen

### ISSUE THREAD

**Issue by KeyboardInterrupt** [AlbianWarp/AlbianWarpClient#40]
If you Stay logged in, and switch Worlds, weird stuff happens.

One Effect, is that you are added to your contact list. (probably user_of_this_world not set properly)

We need a mechanism to detect a World switch and react accordingly, by resetting Variables and stuff...

**Comment by KeyboardInterrupt** [comment]
![image](https://user-images.githubusercontent.com/26553592/45932160-a29d5200-bf78-11e8-9971-44bf1b140f16.png)

**Comment by Amaikokonut** [comment]
With the caos line `OUTS WNAM` you can detect this. If the user is on the world-switcher this will return "Startup"

**Comment by KeyboardInterrupt** [comment]
Yes I thought that the `WNAM` will be critical to this Feature.

While this feature is firstly needed to detect new worlds, and if the Player is in the Menu to ensure online Functionality is paused. and reinitialized whenever a world switch occurred, do you know of a way to further uniquely Identify a world for online registration purpose?

**Comment by KeyboardInterrupt** [comment]
This is made obsolete by the Switch to ReBabel
